steps:

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'docker'
    args:
      - build
      - -f
      - models/Dockerfile
      - -t
      - ${_REGISTRY_BASE}/models:$SHORT_SHA
      - -t
      - ${_REGISTRY_BASE}/models:${_SAFE_BRANCH}
      - '.'
    dir: '.'
    secretEnv: ['API_KEY', 'API_SECRET', 'ACCESS_TOKEN', 'ACCESS_SECRET', 'BEARER_TOKEN', 'CLIENT_ID', 'CLIENT_SECRET']

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'docker'
    args:
      - build
      - -f
      - dagster-image/Dockerfile
      - -t
      - ${_REGISTRY_BASE}/dagster-image:$SHORT_SHA
      - -t
      - ${_REGISTRY_BASE}/dagster-image:${_SAFE_BRANCH}
      - '.'
    dir: '.'

availableSecrets:
  secretManager:
  - versionName: projects/ml-dev-403200/secrets/twitter_api_key/versions/latest
    env: 'API_KEY'
  - versionName: projects/ml-dev-403200/secrets/twitter_api_secret/versions/latest
    env: 'API_SECRET'
  - versionName: projects/ml-dev-403200/secrets/twitter_access_token/versions/latest
    env: 'ACCESS_TOKEN'
  - versionName: projects/ml-dev-403200/secrets/twitter_access_secret/versions/latest
    env: 'ACCESS_SECRET'
  - versionName: projects/ml-dev-403200/secrets/twitter_bearer_token/versions/latest
    env: 'BEARER_TOKEN'
  - versionName: projects/ml-dev-403200/secrets/twitter_client_id/versions/latest
    env: 'CLIENT_ID'
  - versionName: projects/ml-dev-403200/secrets/twitter_client_secret/versions/latest
    env: 'CLIENT_SECRET'


options:
  dynamic_substitutions: true
images:
  - '${_REGISTRY_BASE}/models:$SHORT_SHA'
  - '${_REGISTRY_BASE}/models:${_SAFE_BRANCH}'
  - '${_REGISTRY_BASE}/dagster-image:$SHORT_SHA'
  - '${_REGISTRY_BASE}/dagster-image:${_SAFE_BRANCH}'
timeout: 500s
substitutions:
  _SAFE_BRANCH: ${BRANCH_NAME//\//-}
  _REGISTRY_BASE: australia-southeast1-docker.pkg.dev/ml-dev-403200/dagster-docker


#  _DAGS_DIRECTORY: dags/.
#  _DAGS_BUCKET: us-central1-featurepipe-0a1e7485-bucket #us-central1-automation-serv-2096585b-bucket

#930064416314@cloudbuild.gserviceaccount.com

#gcloud projects add-iam-policy-binding  ml-dev-403200 --member='serviceAccount:229198640655@cloudbuild.gserviceaccount.com' --role='roles/secretmanager.secretAccessor'

# gcloud builds submit --config cloudbuild.yaml SOURCE_CODE

# PN=$(gcloud projects describe ml-dev-403200 --format="value(projectNumber)")
# CLOUD_BUILD_SERVICE_AGENT="service-229198640655@gcp-sa-cloudbuild.iam.gserviceaccount.com"
# gcloud projects add-iam-policy-binding ml-dev-403200 \
#   --member="serviceAccount:${CLOUD_BUILD_SERVICE_AGENT}" \
#   --role="roles/secretmanager.admin"

